server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /media/ {
        rewrite ^/media/(.*)$ /$1 break;
        add_header Access-Control-Allow-Origin * always;
    }
}
